# Dumsi Configuration File

# General Settings
language: "ne"  # Options: "en" (English), "ne" (Nepali)
debug: true

# Speech Recognition Settings
speech_recognition:
  engine: "speechrecognition"
  energy_threshold: 300
  record_timeout: 3
  phrase_timeout: 3
  recognition_language: "ne-NP"  # For Nepali

# Text to Speech Settings
text_to_speech:
  engine: "gtts"
  language: "ne"  # For Nepali
  gender: "male"
  speed_factor: 0.95

# NLP Settings
nlp:
  model: "basic"
  language: "ne"

# Robot Control Settings
robot_control:
  enabled: false
  servo_pins:
    head: 18
    left_arm: 23
    right_arm: 24
  movement_speed: 0.8

# Theme Settings
theme:
  sound_effects:
    startup: "data/audio_samples/startup.mp3"
    shutdown: "data/audio_samples/shutdown.mp3"
    error: "data/audio_samples/error.mp3"
    success: "data/audio_samples/success.mp3"